paths:
  manifesto_snpinfo_pref: "../../sandbox/1000g_biall_snpinfo.human_ancestor.archaic.yri.outgroup.strictmask.manifesto" # NOTE: this cna be generated aside from Zenodo (see README)
  chrom_sizes: "../../trace_zenodo/data/metadata/hg38.chrom.sizes"
  strict_mask: "../../trace_zenodo/data/metadata/hg38_strictmask.bed"
  centromeres: "../../trace_zenodo/data/metadata/centromeres_grch38.singer_exclude_regions.bed"
  gencode: "../../trace_zenodo/data/metadata/gencode.v49.protein_coding.simple.bed"


enrichments:
  datasets:
    EUR: "../../trace_zenodo/data/tables/trace_t15000_eur.csv"
    OCN: "../../trace_zenodo/data/tables/trace_t15000_ocn.csv"
    SAS: "../../trace_zenodo/data/tables/trace_t15000_sas.csv"
    EAS: "../../trace_zenodo/data/tables/trace_t15000_eas.csv"
    LWK: "../../trace_zenodo/data/tables/trace_t15000_eafr.csv"
    YRI: "../../trace_zenodo/data/tables/trace_t15000_wafr.csv"
